In [230]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
np.set_printoptions(threshold=np.inf)

In [231]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR

## Mess (Hr)

In [232]:
dataset = pd.read_csv('Mess(hr)/Mess(hr).csv')
dataset

,Grievance Subject,Hostel,Transaction Mode,Bank used by Payee,Transaction Number,Account Number of Payee,Grievance Description,Attached Documents,Days till response
0,Not Reqd,N,CHEQUE,ICICI,1761066513,955710000000,Not Reqd,Not Reqd,11
1,Not Reqd,I,CHEQUE,HDFC,1893755115,919483000000,Not Reqd,Not Reqd,12
2,Not Reqd,I,NEFT,HDFC,1775178520,946425000000,Not Reqd,Not Reqd,6
3,Not Reqd,L,PAYTM,HDFC,1010544585,924271000000,Not Reqd,Not Reqd,6
4,Not Reqd,B,NEFT,HDFC,1296796242,990537000000,Not Reqd,Not Reqd,10
5,Not Reqd,H,CHEQUE,ICICI,1701715302,915368000000,Not Reqd,Not Reqd,7
6,Not Reqd,PG,CHEQUE,ICICI,1612845749,902984000000,Not Reqd,Not Reqd,7
7,Not Reqd,A,DD,ICICI,1831049838,922215000000,Not Reqd,Not Reqd,12
8,Not Reqd,L,CHEQUE,SBI,1546496994,998344000000,Not Reqd,Not Reqd,6
9,Not Reqd,I,NEFT,SBI,1566630364,953576000000,Not Reqd,Not Reqd,9
10,Not Reqd,H,CHALLAN,ICICI,1972069453,995948000000,Not Reqd,Not Reqd,8
11,Not Reqd,N,NEFT,ICICI,1386028918,987567000000,Not Reqd,Not Reqd,7
12,Not Reqd,N,CHEQUE,HDFC,1321337058,926862000000,Not Reqd,Not Reqd,9
13,Not Reqd,K,CHALLAN,SBI,1538166021,972961000000,Not Reqd,Not Reqd,11
14,Not Reqd,PG,NEFT,ICICI,1461823103,943380000000,Not Reqd,Not Reqd,3
15,Not Reqd,K,DD,ICICI,1861695090,943849000000,Not Reqd,Not Reqd,13
16,Not Reqd,B,DD,SBI,1977635728,904240000000,Not Reqd,Not Reqd,11
17,Not Reqd,E,PAYTM,SBI,1185236196,944588000000,Not Reqd,Not Reqd,13
18,Not Reqd,N,CHEQUE,HDFC,1804805964,953179000000,Not Reqd,Not Reqd,9
19,Not Reqd,H,CHEQUE,SBI,1576723475,971684000000,Not Reqd,Not Reqd,7
20,Not Reqd,K,DD,ICICI,1011221546,960558000000,Not Reqd,Not Reqd,13
21,Not Reqd,I,NEFT,HDFC,1562372372,981555000000,Not Reqd,Not Reqd,6
22,Not Reqd,B,NEFT,HDFC,1717884256,907245000000,Not Reqd,Not Reqd,10
23,Not Reqd,H,NEFT,ICICI,1597378377,906471000000,Not Reqd,Not Reqd,5
24,Not Reqd,L,PAYTM,SBI,1008882757,929512000000,Not Reqd,Not Reqd,7
25,Not Reqd,M,CHEQUE,HDFC,1194255569,915962000000,Not Reqd,Not Reqd,10
26,Not Reqd,N,DD,HDFC,1603047509,958527000000,Not Reqd,Not Reqd,9
27,Not Reqd,I,DD,SBI,1301725943,982940000000,Not Reqd,Not Reqd,6
28,Not Reqd,L,PAYTM,HDFC,1083466337,993520000000,Not Reqd,Not Reqd,6
29,Not Reqd,K,CHEQUE,ICICI,1483147745,963558000000,Not Reqd,Not Reqd,13
30,Not Reqd,I,NEFT,HDFC,1439543637,944784000000,Not Reqd,Not Reqd,6
31,Not Reqd,L,CHEQUE,SBI,1743766226,930302000000,Not Reqd,Not Reqd,6
32,Not Reqd,K,CHEQUE,SBI,1898419493,984896000000,Not Reqd,Not Reqd,11
33,Not Reqd,L,CHALLAN,ICICI,1521696939,970530000000,Not Reqd,Not Reqd,11
34,Not Reqd,J,PAYTM,SBI,1298763252,967358000000,Not Reqd,Not Reqd,9
35,Not Reqd,I,DD,ICICI,1974176721,914010000000,Not Reqd,Not Reqd,11
36,Not Reqd,PG,PAYTM,ICICI,1175443079,985643000000,Not Reqd,Not Reqd,7
37,Not Reqd,L,CHEQUE,HDFC,1315497669,944765000000,Not Reqd,Not Reqd,7
38,Not Reqd,A,NEFT,HDFC,1917428707,943247000000,Not Reqd,Not Reqd,10
39,Not Reqd,A,CHEQUE,ICICI,1148066016,935567000000,Not Reqd,Not Reqd,13
40,Not Reqd,G,PAYTM,SBI,1442432731,912939000000,Not Reqd,Not Reqd,10
41,Not Reqd,N,NEFT,ICICI,1736345795,977906000000,Not Reqd,Not Reqd,7
42,Not Reqd,A,NEFT,HDFC,1692638623,979000000000,Not Reqd,Not Reqd,10
43,Not Reqd,H,CHEQUE,HDFC,1940754922,919731000000,Not Reqd,Not Reqd,5
44,Not Reqd,B,PAYTM,SBI,1758688106,964703000000,Not Reqd,Not Reqd,9
45,Not Reqd,E,CHEQUE,SBI,1225648659,948852000000,Not Reqd,Not Reqd,14
46,Not Reqd,G,CHALLAN,SBI,1507346424,968666000000,Not Reqd,Not Reqd,12
47,Not Reqd,I,CHEQUE,SBI,1907181731,997933000000,Not Reqd,Not Reqd,7
48,Not Reqd,H,NEFT,ICICI,1995870785,950138000000,Not Reqd,Not Reqd,5

In [233]:
X = dataset.iloc[:, 1:4].values
Y = dataset.iloc[:, 8].values

In [234]:
# Save Encoder Objects for new incoming data
import pickle
encx0 = LabelEncoder().fit(X[:,0])
encx1 = LabelEncoder().fit(X[:,1])
encx2 = LabelEncoder().fit(X[:,2])
filename = 'Mess(hr)/Mess(hr)encx0.sav'
pickle.dump(encx0,open(filename,'wb'))
filename = 'Mess(hr)/Mess(hr)encx1.sav'
pickle.dump(encx1,open(filename,'wb'))
filename = 'Mess(hr)/Mess(hr)encx2.sav'
pickle.dump(encx2,open(filename,'wb'))

In [235]:
X[:,0] = encx0.transform(X[:,0])
X[:,1] = encx1.transform(X[:,1])
X[:,2] = encx2.transform(X[:,2])
onehotencoder = OneHotEncoder(categorical_features=[0,1,2])
onehenc = onehotencoder.fit(X)
filename = 'Mess(hr)/Mess(hr)onehenc.sav'
pickle.dump(onehenc,open(filename,'wb'))
X = onehenc.transform(X).toarray()
ar = np.array([10,1,1])
ar = ar.reshape(1,-1)
kar=onehenc.transform(ar).toarray()
print(kar)
print(len(X[0]))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 1. 0.]]
20

In [236]:
k = list()
for i in range(20):
    if i!=0 and i!=12 and i!=17:
        k.append(i)
X = X[:,k]
kar = kar[:,k]

In [237]:
print(len(X[0]))

17

## SVR

In [238]:
from sklearn.model_selection import train_test_split

In [239]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.2, random_state = 0)

In [240]:
model1 = SVR(kernel='rbf')
model1.fit(X_train,Y_train)
Y_pred = model1.predict(X_test)

In [241]:
Y_pred

array([8.92320151, 8.83116842, 9.17595093, 8.46880509, 9.0988148 ,
       8.4140806 , 8.65264704, 8.75729675, 8.98116298, 8.16155869])

In [242]:
Y_test

array([13, 10,  9,  6, 11,  7,  9, 10, 12,  8])

In [243]:
from sklearn.model_selection import GridSearchCV
parameters = [{'C':[1,10,100,1000], 'kernel': ['rbf'], 'gamma':[0.05,0.01,0.001,0.0001]},
             {'C':[100,200,300,400], 'kernel': ['poly'], 'gamma':[0.05,0.06,0.07,0.08,0.09,0.1]},
             {'C':[1,10,100,1000], 'kernel': ['sigmoid'], 'gamma':[0.05,0.01,0.001,0.0001]}]
gridsearch = GridSearchCV(estimator=model1,
                         param_grid=parameters,
                         scoring='r2',
                         cv=10)
gridsearch = gridsearch.fit(X_train,Y_train)
print(gridsearch.best_score_)
print(gridsearch.best_params_)

0.044359634022896555
{'C': 1000, 'gamma': 0.001, 'kernel': 'rbf'}

## Random Forest

In [244]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.2, random_state = 0)

In [245]:
model2 = RandomForestRegressor(n_estimators=970, criterion='mse',random_state=0)
model2 = model2.fit(X,Y)

In [246]:
Y_pred = model2.predict(X_test)
print(Y_pred)
print(Y_test)

[12.72680412  9.92783505  9.18865979  6.18556701 11.02061856  6.91958763
  9.02268041 10.03917526 11.67835052  7.45360825]
[13 10  9  6 11  7  9 10 12  8]

In [247]:
from sklearn.model_selection import GridSearchCV
parameters = [{'n_estimators':[950,960,970,980,990,1000], 'criterion':['mse']}]
grid_search = GridSearchCV(estimator=model2,
                          param_grid=parameters,
                          scoring='r2',
                          cv=10)
grid_search = grid_search.fit(X,Y)
print(grid_search.best_score_)
print(grid_search.best_params_)

0.5025834689186863
{'criterion': 'mse', 'n_estimators': 970}

In [248]:
import pickle
filename = 'Mess(hr)/Mess(hr)model.sav'
pickle.dump(model2,open(filename,'wb'))

In [249]:
loaded_model = pickle.load(open(filename, 'rb'))
result = loaded_model.predict(kar)
print(result)
from sklearn.metrics import r2_score
print(r2_score(Y_test,Y_pred))

[10.66494845]
0.9868043737847992

In [207]:
from sklearn.preprocessing import LabelEncoder
c = ['France', 'UK', 'US', 'US', 'UK', 'China', 'France']
enc = LabelEncoder().fit(c)
encoded = enc.transform(c)
print(encoded)

enc.transform(['France'])

[1 2 3 3 2 0 1]

array([1])