In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
np.set_printoptions(threshold=np.inf)

In [2]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d

## Scholarship Portal

In [3]:
dataset = pd.read_csv('scholarship_disbursement/scholarship_disbursement.csv')
dataset

,Grievance Subject,Current Marks,Applied Course,Scholarship Category,Bank used,Account Number of the scholarship holder,Money released or not (Filled by Commitee Member),Mode of transfer used (Filled by Commitee Member if money released),Period of Scholarship,Grievance Description,Attached Documents,Days till response,Importance
0,NaN,8.542,ENC,4,ICICI,2560050000000,No,DD,2019,Not Reqd,Not Reqd,10,Major
1,NaN,9.091,COE,3,HDFC,8885800000000,No,DD,2018,Not Reqd,Not Reqd,7,Minor
2,NaN,9.735,BIOTECH,1,HDFC,8529260000000,Yes,CHEQUE,2018,Not Reqd,Not Reqd,7,Minor
3,NaN,9.366,CIVIL,3,HDFC,5693530000000,No,PAYTM,2018,Not Reqd,Not Reqd,8,Minor
4,NaN,8.664,CIVIL,2,HDFC,6786660000000,Yes,CHALLAN,2018,Not Reqd,Not Reqd,7,Major
5,NaN,8.849,MEE,2,ICICI,1929060000000,Yes,PAYTM,2019,Not Reqd,Not Reqd,6,Major
6,NaN,9.028,COE,3,ICICI,1643970000000,Yes,PAYTM,2019,Not Reqd,Not Reqd,6,Major
7,NaN,9.686,ENC,4,ICICI,2069740000000,Yes,CHEQUE,2018,Not Reqd,Not Reqd,8,Minor
8,NaN,9.676,COE,4,SBI,2766790000000,No,DD,2018,Not Reqd,Not Reqd,12,Minor
9,NaN,8.584,COE,3,SBI,4631890000000,No,DD,2018,Not Reqd,Not Reqd,8,Minor
10,NaN,9.617,ECE,2,ICICI,6333670000000,No,PAYTM,2018,Not Reqd,Not Reqd,9,Major
11,NaN,9.995,CIVIL,3,ICICI,2469670000000,Yes,CHEQUE,2019,Not Reqd,Not Reqd,7,Major
12,NaN,9.485,ENC,1,HDFC,7531060000000,No,NEFT,2019,Not Reqd,Not Reqd,8,Minor
13,NaN,9.911,ELEC,3,SBI,5053110000000,No,CHALLAN,2019,Not Reqd,Not Reqd,8,Minor
14,NaN,9.598,CIVIL,1,ICICI,8776120000000,Yes,PAYTM,2019,Not Reqd,Not Reqd,6,Major
15,NaN,9.736,CHEM,2,ICICI,4834850000000,Yes,DD,2019,Not Reqd,Not Reqd,10,Minor
16,NaN,9.933,COE,4,SBI,6794050000000,Yes,NEFT,2018,Not Reqd,Not Reqd,8,Minor
17,NaN,9.596,ENC,3,SBI,8211910000000,Yes,DD,2018,Not Reqd,Not Reqd,11,Minor
18,NaN,9.525,ELEC,1,HDFC,1909560000000,No,CHEQUE,2019,Not Reqd,Not Reqd,8,Major
19,NaN,8.573,ENC,2,SBI,2703810000000,Yes,CHEQUE,2018,Not Reqd,Not Reqd,6,Major
20,NaN,8.761,ELEC,1,ICICI,8719210000000,Yes,DD,2019,Not Reqd,Not Reqd,5,Major
21,NaN,8.979,CHEM,1,HDFC,5732970000000,Yes,DD,2019,Not Reqd,Not Reqd,10,Minor
22,NaN,9.405,COE,1,HDFC,5395470000000,Yes,CHEQUE,2018,Not Reqd,Not Reqd,5,Minor
23,NaN,9.742,CHEM,3,ICICI,1611510000000,Yes,NEFT,2019,Not Reqd,Not Reqd,7,Minor
24,NaN,9.583,CIVIL,3,SBI,2501210000000,Yes,DD,2019,Not Reqd,Not Reqd,10,Major
25,NaN,8.600,MEE,1,HDFC,1222860000000,No,DD,2018,Not Reqd,Not Reqd,8,Major
26,NaN,9.677,COE,2,HDFC,3370080000000,No,PAYTM,2019,Not Reqd,Not Reqd,9,Minor
27,NaN,8.700,ECE,3,SBI,8543290000000,No,CHALLAN,2018,Not Reqd,Not Reqd,6,Minor
28,NaN,9.414,BIOTECH,1,HDFC,2546620000000,Yes,PAYTM,2019,Not Reqd,Not Reqd,9,Major
29,NaN,9.287,BIOTECH,4,ICICI,7837300000000,No,PAYTM,2018,Not Reqd,Not Reqd,8,Minor
30,NaN,8.924,COE,4,HDFC,1784430000000,No,CHALLAN,2018,Not Reqd,Not Reqd,11,Minor
31,NaN,9.762,MEE,4,SBI,3835000000000,Yes,PAYTM,2018,Not Reqd,Not Reqd,7,Minor
32,NaN,9.005,CIVIL,4,SBI,4626360000000,Yes,NEFT,2018,Not Reqd,Not Reqd,9,Major
33,NaN,9.988,ECE,2,ICICI,4450800000000,No,CHEQUE,2018,Not Reqd,Not Reqd,6,Major
34,NaN,9.770,CIVIL,1,SBI,7271650000000,No,CHALLAN,2019,Not Reqd,Not Reqd,9,Minor
35,NaN,9.067,MEE,4,ICICI,6117250000000,Yes,CHEQUE,2018,Not Reqd,Not Reqd,8,Minor
36,NaN,9.129,ECE,4,ICICI,1229460000000,No,CHALLAN,2018,Not Reqd,Not Reqd,11,Major
37,NaN,9.959,ENC,1,HDFC,7904840000000,Yes,DD,2018,Not Reqd,Not Reqd,11,Minor
38,NaN,9.592,CIVIL,4,HDFC,2594210000000,Yes,PAYTM,2018,Not Reqd,Not Reqd,11,Minor
39,NaN,8.627,ENC,1,ICICI,8709100000000,No,DD,2018,Not Reqd,Not Reqd,9,Minor
40,NaN,8.680,ENC,2,SBI,3581540000000,Yes,DD,2019,Not Reqd,Not Reqd,10,Major
41,NaN,8.553,ELEC,1,ICICI,7595280000000,Yes,CHEQUE,2018,Not Reqd,Not Reqd,4,Major
42,NaN,9.826,CHEM,2,HDFC,2709010000000,Yes,DD,2019,Not Reqd,Not Reqd,8,Minor
43,NaN,9.856,ENC,1,HDFC,4807950000000,Yes,DD,2019,Not Reqd,Not Reqd,8,Minor
44,NaN,9.072,CIVIL,1,SBI,7788330000000,Yes,DD,2019,Not Reqd,Not Reqd,11,Major
45,NaN,8.748,CIVIL,3,SBI,3664180000000,Yes,CHALLAN,2018,Not Reqd,Not Reqd,8,Minor
46,NaN,8.773,CIVIL,1,SBI,2795460000000,Yes,CHALLAN,2018,Not Reqd,Not Reqd,9,Minor
47,NaN,8.701,ECE,2,SBI,7892020000000,Yes,CHALLAN,2019,Not Reqd,Not Reqd,9,Minor
48,NaN,9.490,ENC,3,ICICI,1250360000000,Yes,CHEQUE,2018,Not Reqd,Not Reqd,7,Major

In [4]:
k = [1,2,3,4,7,8]
X = dataset.iloc[:, k].values
Y = dataset.iloc[:, 11].values
len(X[0])

6

In [6]:
# Save Encoder Objects for new incoming data
import pickle
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
encx1 = LabelEncoder().fit(X[:,1])
encx3 = LabelEncoder().fit(X[:,3])
encx4 = LabelEncoder().fit(X[:,4])
filename = 'scholarship_disbursement/scholarship_disbursementencx1.sav'
pickle.dump(encx1,open(filename,'wb'))
filename = 'scholarship_disbursement/scholarship_disbursementencx3.sav'
pickle.dump(encx3,open(filename,'wb'))
filename = 'scholarship_disbursement/scholarship_disbursementencx4.sav'
pickle.dump(encx4,open(filename,'wb'))

In [7]:
data = [8.2,'COE',3,'SBI','DD',2019]

In [8]:
X[:,1] = encx1.transform(X[:,1])
X[:,3] = encx3.transform(X[:,3])
X[:,4] = encx4.transform(X[:,4])
print(max(X[:,4]))
onehotencoder = OneHotEncoder(categorical_features=[1,2,3,4,5])
onehenc = onehotencoder.fit(X)
filename = 'scholarship_disbursement/scholarship_disbursementonehenc.sav'
pickle.dump(onehenc,open(filename,'wb'))
X = onehenc.transform(X).toarray()
d = encx1.transform([data[1]])
data[1] = d[0]
d = encx3.transform([data[3]])
data[3] = d[0]
d = encx4.transform([data[4]])
data[4] = d[0]
ar = np.array(data)
print(data)
ar = ar.reshape(1,-1)
kar=onehenc.transform(ar).toarray()
print(kar)
print(len(X[0]))

4
[8.2, 3, 3, 2, 2, 2019]
[[0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  1.  0.  0.  1.
  0.  0.  0.  1.  8.2]]
23

In [9]:
k = list()
notlist = [0,8,12,15,20]
for i in range(23):
    if i not in notlist:
        k.append(i)
X = X[:,k]
kar = kar[:,k]

In [10]:
print(len(X[0]))

18

## SVR

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.2, random_state = 0)

In [13]:
model1 = SVR(kernel='rbf')
model1.fit(X_train,Y_train)
Y_pred = model1.predict(X_test)

In [14]:
Y_pred

array([7.84694356, 7.94152886, 7.50489555, 8.01204543, 8.49331696,
       8.16509968, 8.33162615, 8.45945541, 7.62364783, 7.34523722])

In [15]:
Y_test

array([ 8,  7,  9, 11,  9, 11,  9, 10,  8,  9])

In [16]:
from sklearn.model_selection import GridSearchCV
parameters = [{'C':[1,10,100,1000], 'kernel': ['rbf'], 'gamma':[0.05,0.01,0.001,0.0001]},
             {'C':[100,200,300,400], 'kernel': ['poly'], 'gamma':[0.05,0.06,0.07,0.08,0.09,0.1]},
             {'C':[1,10,100,1000], 'kernel': ['sigmoid'], 'gamma':[0.05,0.01,0.001,0.0001]}]
gridsearch = GridSearchCV(estimator=model1,
                         param_grid=parameters,
                         scoring='r2',
                         cv=10)
gridsearch = gridsearch.fit(X_train,Y_train)
print(gridsearch.best_score_)
print(gridsearch.best_params_)

-1.2753744258481654
{'C': 1000, 'gamma': 0.0001, 'kernel': 'sigmoid'}

## Random Forest

In [17]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.2, random_state = 0)

In [18]:
model2 = RandomForestRegressor(n_estimators=50, criterion='mse',random_state=0)
model2 = model2.fit(X,Y)

In [19]:
Y_pred = model2.predict(X)
print(Y_pred)
print(Y_test)
print(r2_score(Y,Y_pred))

[ 9.8   7.44  7.08  7.82  7.38  6.92  6.24  7.78 11.16  8.02  8.36  7.
  8.44  7.52  7.    9.14  8.66 10.24  7.46  6.28  6.6   9.64  5.9   7.14
  9.58  7.92  8.6   6.76  8.82  8.48  9.98  7.66  9.52  6.46  8.74  7.4
 10.1   9.72  9.96  8.74  9.7   4.58  8.42  8.58 10.48  8.06  8.76  8.52
  7.2 ]
[ 8  7  9 11  9 11  9 10  8  9]

NameError: name 'r2_score' is not defined

In [20]:
from sklearn.model_selection import GridSearchCV
parameters = [{'n_estimators':[10,20,30,40,50], 'criterion':['mse']}]
grid_search = GridSearchCV(estimator=model2,
                          param_grid=parameters,
                          scoring='r2',
                          cv=10)
grid_search = grid_search.fit(X,Y)
print(grid_search.best_score_)
print(grid_search.best_params_)

-0.38407377430527745
{'criterion': 'mse', 'n_estimators': 50}

In [21]:
import pickle
filename = 'scholarship_disbursement/scholarship_disbursementmodel.sav'
pickle.dump(model2,open(filename,'wb'))

In [22]:
loaded_model = pickle.load(open(filename, 'rb'))
result = loaded_model.predict(kar)
print(result)
from sklearn.metrics import r2_score

[8.28]

## Classification

In [24]:
Y2 = dataset.iloc[:,-1].values

In [25]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report

In [26]:
classifier = RandomForestClassifier(n_estimators=100,criterion='gini')
classifier = classifier.fit(X,Y2)
y_pred = classifier.predict(X)
print(classification_report(Y2,y_pred))

             precision    recall  f1-score   support

     Major        1.00      1.00      1.00        20
      Minor       1.00      1.00      1.00        29

avg / total       1.00      1.00      1.00        49

In [27]:
filename = 'scholarship_disbursement/scholarship_disbursementClassmodel.sav'
pickle.dump(classifier,open(filename,'wb'))